name: Deploy app on release

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: production-app
  cancel-in-progress: false

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out release
        uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: tracker/package-lock.json
      - name: Install tracker dependencies
        run: npm ci --prefix tracker
      - name: Deploy tracker application
        run: make deploy-app
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
